### ISSUE TITLE
Populate database with predefined users

### ISSUE THREAD

**Issue by stellakimnguyen** [car12lin12/InstaBaddies#27]
As we are only working on the follow feature, populate the database with "hard-coded" users to test:
- Only need a few users
- Following list attribute
- Followers list attribute
- Go directly in the database (for now)

Set up: 
- Read *TO RUN* in the README to help get started
- Create MongoDB account
- Create cluster (look for the green light!)
- Connect > Connect Application > Copy url string (write your URL in the README)
- Go to project folder
- Create .env file in *server* folder
  - Write: MONGODB_URL = your_url

Create users in database:
- Use Postman/VS Code extension (REST client)/preferred service
- Follow the User Schema to make a post request (InstaBaddies > server > models > User.js)
  - Use the HTTP method *POST*
  - Path: localhost:3002/users
  - Use the User Schema to create the users (3) (only the required attributes)
     - In Postman, make sure the body is raw
     - and in Headers, make sure the Content-Type is application/json
  - Send

**Comment by YordanEvro** [comment]
Created predefined users for mongoDB atlas cloud database using the node.js app. An example of a user stored in the database: 
{"_id":{"$oid":"5e45f16691d40b34605fbcbf"},"posts":[],"comments":[],"following":[],"followers":[],"username":"yordan","email":"carlin@yahoo.com","password":"$2b$08$Nxm6q6HpUutwTiisxFEpbetqvueTtxJLCrC1k21pLvKArO3bHLC","__v":{"$numberInt":"0"}}
