### ISSUE TITLE
Finalized UML diagrams

### ISSUE THREAD

**Issue by car12lin12** [car12lin12/InstaBaddies#73]

**Comment by jam009** [comment]
![object Model](https://user-images.githubusercontent.com/60364022/78151311-792f7300-7406-11ea-81ed-87d0850ffd49.png)

**Comment by jam009** [comment]
![High Level](https://user-images.githubusercontent.com/60364022/78151511-ac720200-7406-11ea-9e3f-9497025507ef.png)

**Comment by jam009** [comment]
![High Level](https://user-images.githubusercontent.com/60364022/78152029-46d24580-7407-11ea-84ce-0ee09454eb29.png)
![Notifications   Follow](https://user-images.githubusercontent.com/60364022/78152043-4afe6300-7407-11ea-9bc0-23c2123ea21e.png)
![Post Actions](https://user-images.githubusercontent.com/60364022/78152348-ad576380-7407-11ea-8e61-7a4e3ee0baea.png)

**Comment by jam009** [comment]
![Comment Actions](https://user-images.githubusercontent.com/60364022/78152500-e1328900-7407-11ea-89e8-c6e3347cc403.png)
![User Actions](https://user-images.githubusercontent.com/60364022/78152570-fdcec100-7407-11ea-8aca-dc6960791b6e.png)

**Comment by jam009** [comment]
![MVC](https://user-images.githubusercontent.com/60364022/78152791-4d14f180-7408-11ea-93d9-c95152b9330f.png)

**Comment by jam009** [comment]
![High Level (1)](https://user-images.githubusercontent.com/60364022/78158011-bac41c00-740e-11ea-89f2-75d144a54ee3.png)

**Comment by car12lin12** [comment]
Great job
